<?php
/**
 * Simple WordPress Admin Panel for FaresKart
 * This provides a basic admin interface for customizing content
 */

session_start();

// Simple authentication (you can change these credentials)
$admin_username = 'admin';
$admin_password = 'fareskart2024';

// Check if user is logged in
if (!isset($_SESSION['admin_logged_in'])) {
    // Show login form
    if ($_POST && isset($_POST['username']) && isset($_POST['password'])) {
        if ($_POST['username'] === $admin_username && $_POST['password'] === $admin_password) {
            $_SESSION['admin_logged_in'] = true;
        } else {
            $error = 'Invalid credentials';
        }
    }
    
    if (!isset($_SESSION['admin_logged_in'])) {
        ?>
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>FaresKart Admin Login</title>
            <style>
                body { font-family: Arial, sans-serif; background: #f5f5f5; margin: 0; padding: 50px; }
                .login-container { max-width: 400px; margin: 0 auto; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
                .form-group { margin-bottom: 20px; }
                label { display: block; margin-bottom: 5px; font-weight: bold; }
                input[type="text"], input[type="password"] { width: 100%; padding: 10px; border: 1px solid #ddd; border-radius: 4px; box-sizing: border-box; }
                button { background: #1a3e72; color: white; padding: 12px 20px; border: none; border-radius: 4px; cursor: pointer; width: 100%; }
                button:hover { background: #0d2a57; }
                .error { color: red; margin-bottom: 20px; }
                h1 { text-align: center; color: #1a3e72; margin-bottom: 30px; }
            </style>
        </head>
        <body>
            <div class="login-container">
                <h1>FaresKart Admin</h1>
                <?php if (isset($error)): ?><div class="error"><?php echo $error; ?></div><?php endif; ?>
                <form method="POST">
                    <div class="form-group">
                        <label>Username:</label>
                        <input type="text" name="username" required>
                    </div>
                    <div class="form-group">
                        <label>Password:</label>
                        <input type="password" name="password" required>
                    </div>
                    <button type="submit">Login</button>
                </form>
            </div>
        </body>
        </html>
        <?php
        exit;
    }
}

// Handle form submissions
if ($_POST && isset($_POST['action'])) {
    $config_file = 'wordpress-config.php';
    
    if ($_POST['action'] === 'save') {
        $config_data = "<?php\n// FaresKart WordPress Configuration\n";
        $config_data .= "// Auto-generated by admin panel\n\n";
        
        foreach ($_POST as $key => $value) {
            if ($key !== 'action' && $key !== 'submit') {
                $config_data .= "define('FARESKART_" . strtoupper($key) . "', '" . addslashes($value) . "');\n";
            }
        }
        
        file_put_contents($config_file, $config_data);
        $success = 'Settings saved successfully!';
    }
}

// Load current configuration
$current_config = [];
if (file_exists('wordpress-config.php')) {
    include 'wordpress-config.php';
    // Extract values from constants
    $current_config = [
        'hero_title' => defined('FARESKART_HERO_TITLE') ? FARESKART_HERO_TITLE : 'Find & Book Your Perfect Trip',
        'hero_subtitle' => defined('FARESKART_HERO_SUBTITLE') ? FARESKART_HERO_SUBTITLE : 'Discover amazing deals on flights, hotels, and vacation packages around the world',
        'about_text' => defined('FARESKART_ABOUT_TEXT') ? FARESKART_ABOUT_TEXT : 'FaresKart is online travel agency delivering top-notch service worldwide...',
        'contact_address' => defined('FARESKART_CONTACT_ADDRESS') ? FARESKART_CONTACT_ADDRESS : '123 Travel St, Suite 100',
        'contact_phone' => defined('FARESKART_CONTACT_PHONE') ? FARESKART_CONTACT_PHONE : '+1 (555) 123-4567',
        'contact_email' => defined('FARESKART_CONTACT_EMAIL') ? FARESKART_CONTACT_EMAIL : 'support@fareskart.com',
        'customers_number' => defined('FARESKART_CUSTOMERS_NUMBER') ? FARESKART_CUSTOMERS_NUMBER : '2,000,000+',
        'airlines_number' => defined('FARESKART_AIRLINES_NUMBER') ? FARESKART_AIRLINES_NUMBER : '600+',
        'destinations_number' => defined('FARESKART_DESTINATIONS_NUMBER') ? FARESKART_DESTINATIONS_NUMBER : '1,000+',
        'experience_years' => defined('FARESKART_EXPERIENCE_YEARS') ? FARESKART_EXPERIENCE_YEARS : '5+'
    ];
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FaresKart Admin Panel</title>
    <style>
        body { font-family: Arial, sans-serif; background: #f5f5f5; margin: 0; padding: 20px; }
        .admin-container { max-width: 1200px; margin: 0 auto; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 30px; padding-bottom: 20px; border-bottom: 2px solid #1a3e72; }
        .header h1 { color: #1a3e72; margin: 0; }
        .logout-btn { background: #dc3545; color: white; padding: 8px 16px; border: none; border-radius: 4px; text-decoration: none; }
        .logout-btn:hover { background: #c82333; }
        .form-section { margin-bottom: 30px; padding: 20px; border: 1px solid #ddd; border-radius: 8px; }
        .form-section h3 { color: #1a3e72; margin-top: 0; }
        .form-row { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 15px; }
        .form-group { margin-bottom: 15px; }
        label { display: block; margin-bottom: 5px; font-weight: bold; color: #333; }
        input[type="text"], input[type="email"], textarea { width: 100%; padding: 10px; border: 1px solid #ddd; border-radius: 4px; box-sizing: border-box; }
        textarea { height: 80px; resize: vertical; }
        .save-btn { background: #28a745; color: white; padding: 12px 30px; border: none; border-radius: 4px; cursor: pointer; font-size: 16px; }
        .save-btn:hover { background: #218838; }
        .success { background: #d4edda; color: #155724; padding: 15px; border-radius: 4px; margin-bottom: 20px; }
        .nav-tabs { display: flex; border-bottom: 1px solid #ddd; margin-bottom: 20px; }
        .nav-tab { padding: 10px 20px; border: none; background: none; cursor: pointer; border-bottom: 2px solid transparent; }
        .nav-tab.active { border-bottom-color: #1a3e72; color: #1a3e72; font-weight: bold; }
        .tab-content { display: none; }
        .tab-content.active { display: block; }
    </style>
</head>
<body>
    <div class="admin-container">
        <div class="header">
            <h1>FaresKart Admin Panel</h1>
            <a href="?logout=1" class="logout-btn">Logout</a>
        </div>

        <?php if (isset($success)): ?>
            <div class="success"><?php echo $success; ?></div>
        <?php endif; ?>

        <div class="nav-tabs">
            <button class="nav-tab active" onclick="showTab('hero')">Hero Section</button>
            <button class="nav-tab" onclick="showTab('about')">About Us</button>
            <button class="nav-tab" onclick="showTab('contact')">Contact Info</button>
            <button class="nav-tab" onclick="showTab('numbers')">Statistics</button>
        </div>

        <form method="POST">
            <input type="hidden" name="action" value="save">

            <!-- Hero Section -->
            <div id="hero" class="tab-content active">
                <div class="form-section">
                    <h3>Hero Section Content</h3>
                    <div class="form-group">
                        <label>Hero Title:</label>
                        <input type="text" name="hero_title" value="<?php echo htmlspecialchars($current_config['hero_title'] ?? ''); ?>">
                    </div>
                    <div class="form-group">
                        <label>Hero Subtitle:</label>
                        <textarea name="hero_subtitle"><?php echo htmlspecialchars($current_config['hero_subtitle'] ?? ''); ?></textarea>
                    </div>
                </div>
            </div>

            <!-- About Us -->
            <div id="about" class="tab-content">
                <div class="form-section">
                    <h3>About Us Content</h3>
                    <div class="form-group">
                        <label>About Text:</label>
                        <textarea name="about_text"><?php echo htmlspecialchars($current_config['about_text'] ?? ''); ?></textarea>
                    </div>
                </div>
            </div>

            <!-- Contact Info -->
            <div id="contact" class="tab-content">
                <div class="form-section">
                    <h3>Contact Information</h3>
                    <div class="form-row">
                        <div class="form-group">
                            <label>Address:</label>
                            <input type="text" name="contact_address" value="<?php echo htmlspecialchars($current_config['contact_address'] ?? ''); ?>">
                        </div>
                        <div class="form-group">
                            <label>Phone:</label>
                            <input type="text" name="contact_phone" value="<?php echo htmlspecialchars($current_config['contact_phone'] ?? ''); ?>">
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Email:</label>
                        <input type="email" name="contact_email" value="<?php echo htmlspecialchars($current_config['contact_email'] ?? ''); ?>">
                    </div>
                </div>
            </div>

            <!-- Statistics -->
            <div id="numbers" class="tab-content">
                <div class="form-section">
                    <h3>Statistics Numbers</h3>
                    <div class="form-row">
                        <div class="form-group">
                            <label>Happy Customers:</label>
                            <input type="text" name="customers_number" value="<?php echo htmlspecialchars($current_config['customers_number'] ?? ''); ?>">
                        </div>
                        <div class="form-group">
                            <label>Airlines:</label>
                            <input type="text" name="airlines_number" value="<?php echo htmlspecialchars($current_config['airlines_number'] ?? ''); ?>">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group">
                            <label>Destinations:</label>
                            <input type="text" name="destinations_number" value="<?php echo htmlspecialchars($current_config['destinations_number'] ?? ''); ?>">
                        </div>
                        <div class="form-group">
                            <label>Experience Years:</label>
                            <input type="text" name="experience_years" value="<?php echo htmlspecialchars($current_config['experience_years'] ?? ''); ?>">
                        </div>
                    </div>
                </div>
            </div>

            <button type="submit" name="submit" class="save-btn">Save All Changes</button>
        </form>
    </div>

    <script>
        function showTab(tabName) {
            // Hide all tab contents
            const tabContents = document.querySelectorAll('.tab-content');
            tabContents.forEach(content => content.classList.remove('active'));
            
            // Remove active class from all tabs
            const navTabs = document.querySelectorAll('.nav-tab');
            navTabs.forEach(tab => tab.classList.remove('active'));
            
            // Show selected tab content
            document.getElementById(tabName).classList.add('active');
            
            // Add active class to clicked tab
            event.target.classList.add('active');
        }
    </script>
</body>
</html>
